SCREEN_WIDTH = 1280 
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROIDS_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MAX_RADIUS = ASTEROIDS_KINDS * ASTEROID_MIN_RADIUS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200 


SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED  = 500
PLAYER_SHOOT_COOLDOWN  = 0.3